# ðŸš¢ **EDA On univeral dataset** ðŸ›³

Welcome my visual journey of titanic Dataset, through the EDA my mission is to uncover the determinants of passenger survival on the Titanic. Through the application of statistical techniques and visually stunning visualizations, my aim to decode the dataset's mysteries.
Loopup through the passangers by age, gender, survival etc.

<!-- ![titanic.jpeg](attachment:32da1561-6b88-45cf-983f-4e7346c33d04.jpeg) -->
<img src="./titanic.jpeg" alt='titanic' style="width:90%; height: 520px;margin-top:40px;">

### as

By seeing this notebook hope you insight some points and I would like to know your opinoin about my work.

So let's move forward

<div style="background-color:#5755FE;color:white;width:100%;height:60px;text-align:center;font-size:22px;font-family:Georgia;font-weight:bolder;border-radius:15px;">
   <h1 style="padding-top:9px;">About Author</h1>
</div>

<div style="font-size:18px;">
    <p>Greeting! I'm <b>Muhammad Jawad</b> current working as a data analyst and am on an exciting journey to master the art of data science. <!--Data is everywhere so let's explore it.--> <br />
        You can see my another notebook to exploring: 
<a href="https://www.kaggle.com/code/mjawad17/eda-google-playstore-app/notebook">EDA on Google-Play-Store-Apps</a>
        </p>

</div>
<div style="text-align: left;">
    <table>
        <tr style="font-size:16px;text-align:center;">
            <th><b>Website</b></th>
            <th><b>Links</b></th>
        </tr>
        <tr>
        </tr>
        <tr>
            <td style="font-size:14px; font-weight:bold;">GitHub</td>
            <td><a href="https://github.com/mj-awad17"><img src="https://img.shields.io/badge/GitHub-Profile-blue?style=for-the-badge&logo=github" alt="GitHub"/></a></td>
        </tr>
        <tr>
            <td style="font-size:14px; font-weight:bold;">LinkedIn</td>
            <td><a href="https://www.linkedin.com/in/muhammad-jawad-86507b201/"><img src="https://img.shields.io/badge/LinkedIn-Profile-blue?style=for-the-badge&logo=linkedin" alt="LinkedIn"/></a></td>
        </tr>
        <tr>
            <td  style="font-size:14px; font-weight:bold;">Gmail</td>
            <td><a href="mailto:jawadrana660@gmail.com"><img src="https://img.shields.io/badge/Gmail-Contact%20Me-red?style=for-the-badge&logo=gmail" alt="Gmail"/></a></td>
        </tr>
    </table>
</div>
<div style="font-size:18px;">Join this illuminating journey through the Titanic dataset, where I engage in comprehensive exploratory data analysis (EDA) to uncover the secrets behind passenger survival on the RMS Titanic. Utilizing statistical tools and visually appealing representations, my aim to reveal the dataset's underlying patters.</div>
<hr />

<div style="font-size:16px;">
    <h1>Acknowledgement</h1>
    <p>
        I would like to acknowledge and express my gratitude to the creators of the Titanic dataset for their generosity in making it publicly available. Additionally, I extend my appreciation to the <em>Kaggle</em> platform for hosting the Titanic Machine Learning competition.    
    </p>
    <h1>Inspiration</h1>
    <p>
        The Titanic data has enormous potential for beginners to succeed as data scientists. Actionable insights can be drawn for 
data scientists to work on, train their models, test, and capture the new Ai era!<br />
        I would like to extend my gratitude to <a href="https://www.kaggle.com/devbilalkhan">Bilal Khan</a>. His working has been a guiding resource, demonstrating the power of thoughtful data analysis and data science.
    </p>
</div>
<hr />

<div style="background-color:#5755FE;color:white;width:100%;height:60px;text-align:center;font-size:22px;font-family:Georgia;font-weight:bolder;border-radius:15px;">
    <h1 style="padding-top:9px;">About Dataset Detail</h1>
</div>

<div style="font-size:18px;">
    <p>
        Let's talk about legendary dataset which is commonly used used for both machine learning and data analysis. Now it's based on two set: Training and test data. However, it contains information about the passengers their fare, cabin and many more. The training set includes passenger information along with the survival outcome, which we'll use to train our machine learning models.
    </p>
        To understand the data better, let's dive into the key columns and their descriptions:
        <ul style="line-height:35px;">
            <li><em><b>Survived:</b></em> Indicates if a passenger survived as 1 or not-survived as 0.</li>
            <li><em><b>Pclass:</b></em> Ticket class, a proxy for socio-economic status (1 = Upper, 2 = Moderate, 3 = Low) classes.</li>
            <li><em><b>Name:</b></em> Passenger's name.</li>
            <li><em><b>Sex:</b></em> Passenger's gender (male & female)</li>
            <li><em><b>Age:</b></em> Passenger's age in years.</li>
            <li><em><b>SibSp:</b></em> Number of siblings/spouses aboard the Titanic.</li>
            <li><em><b>Parch:</b></em> Number of parents/children aboard the Titanic.</li>
        </ul>
</div>

# **Project Goal**

My main aim is to conduct an analysis of the Titanic dataset, with a particular emphasis on identifying the most influential factors in 
predicting passenger survival. 

<!-- ----- -->

_Primary objective is to conduct a detailed analysis of the Titanic dataset to understand the primary factors that influenced passenger survival._

# Import Libraries

Baisc libraries which are used in data analytics and data science

In [ ]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

# Read CSV file

Reading the file through the pandas function. `read_csv`

In [ ]:
train = pd.read_csv('/kaggle/input/titanic/train.csv')
test = pd.read_csv('/kaggle/input/titanic/test.csv')

# Basic Steps

### Train Dataset

In [ ]:
# checking the rows/columns in dataframe
train.shape

In [ ]:
# column name of train dataframe
train.columns

In [ ]:
# checking Info for Dtype
train.info()

In [ ]:
train.sample(5)

### 1. Observation
There are __891 rows__ and __12 columns__ in train dataframe.
   - __Numerical columns__: 7 named as `PassengerId`, `Survived`, `Pclass`, `Age`, `SibSp`, `Parch` and `Fare`.
   - __Categorical columns__: 5 named as `Name`, `Sex`, `Ticket`, `Cabin` and `Embarked`.

In [ ]:
train.describe()

### Statistical Summery

- **`Survived`** is a binary signing where **`1`** represents survival and **`0`** represents non-survival. 
    
    - Mean rate of survival is **`0.383838`** (which is approximately **`38.38%`**), suggesting that less than half of the passengers survived.
â€‹


- **`Pclass`** represents the class of travel. The passengers are spread across three classes 1, 2 and 3. 
   
   - Mean **`Pclass`** of **`2.308642`**, implying that most passengers are in the second and third classes.
â€‹


- **`Age`** of the passengers has a mean of **`29.699118`** years.
   
   - The youngest being **`0.42`** (42) years old and the oldest at **`80`** years. 


__Note:__ The age data is incomplete because total entries are `891` an age have `714`, so out of 714 entries are null values.

### Test Data

In [ ]:
test.sample(5)

In [ ]:
print(f"Total rows and columns in test dataset: {test.shape}")

In [ ]:
# getting missing values from both data set using function
def get_missing_values(df):

    index_names = ["Total", "Missing %", "Data type"]
    columns = df.columns
    missing_values_table = pd.DataFrame(index=index_names, columns=columns)
    for col in columns:
        missing_data = df[col].isnull().sum()
        missing_data_percentage = round((missing_data/df.shape[0])*100, 2)
        missing_values_table.loc[index_names[0],col] = df[col].isnull().sum()
        missing_values_table.loc[index_names[1],col] = missing_data_percentage
        missing_values_table.loc[index_names[2],col] = df[col].dtype
    return missing_values_table

In [ ]:
# Missing values in the Train-dataset
Train_values = get_missing_values(train)
Train_values

In [ ]:
# Missing values in the Test-dataset
Test_values = get_missing_values(train)
Test_values

### 2. Observation


#### _Train Dataset_

- **Entries**: In the training dataset of 891 entries, several columns have missing values:
  - __Age__: `177` missing entries (19.87%).
  
  - __Cabin__: `687` missing entries (77.1%).
  
  - __Embarked__: `2` missing entries (0.22%).
  
#### _Test Dataset_

- **Entries**: In the training dataset of 418 entries, several columns have missing values:
  - __Age__: `86` missing entries (20.57%).
  
  - __Cabin__: `327` missing entries (78.23%).
  
  - __Fare__:`1` missing entries (0.24%).

## Missing Values in plot

In [ ]:
# missing values plot
plt.figure(figsize=(16,4))
sns.heatmap(train.isnull(),yticklabels=False,cbar=False,cmap='viridis')
plt.show()

In [ ]:
plt.figure(figsize=(16,4))
sns.heatmap(test.isnull(),yticklabels=False,cbar=False,cmap='viridis')
plt.show()

- Combine both dataset

In [ ]:
# let's concate the `train` and `test` dataset to see the missing values in one plot
df = pd.concat([train, test], axis=0)

In [ ]:
df

In [ ]:
# total missing values in each columns after concatenate of `train` and `test` data.
df.isnull().sum()

In [ ]:
plt.figure(figsize=(16,4))
sns.heatmap(df.isnull(),yticklabels=False,cbar=False,cmap='viridis')
plt.show()

In [ ]:
# after concate checking the total duplicate values
df.duplicated().sum()

### 3. Observation

Before the concate the train and test dataset both contain three columns in which have missing value.
After the concate the above dataset the one more columns: 

- `Survived` missing entities __418__ .


<!-- #### _Train Dataset_

- **Entries**: In the training dataset of 891 entries, several columns have missing values:
  - __Age__: `177` missing entries (19.87%).
  
  - __Cabin__: `687` missing entries (77.1%).
  
  - __Embarked__: `2` missing entries (0.22%).
  
#### _Test Dataset_

- **Entries**: In the training dataset of 418 entries, several columns have missing values:
  - __Age__: `86` missing entries (20.57%).
  
  - __Cabin__: `327` missing entries (78.23%).
  
  - __Fare__:`1` missing entries (0.24%). -->

In [ ]:
first_title = 'Total Passangers'
plt.title(first_title)
sns.countplot(x='Sex', data=df, hue="Survived")
plt.show()

In [ ]:
# Grouping the age column
bins = [0, 5, 10, 15, 18, 40, 80]
labels = ['0-5', '6-10', '11-15', '16-18', '19-40', '41-80']
df['Age_group'] = pd.cut(df['Age'], bins=bins, labels=labels)
plt.figure(figsize=(13,5))
first_title = 'Total Passangers'
plt.title(first_title)
sns.countplot(x='Age_group', data=df, hue="Survived")
plt.show()

In [ ]:
# kdeplot of survival counts
plt.figure(figsize=(12,4))
sns.kdeplot(df['Survived'],color='blue',shade=True)
plt.show()

In [ ]:
plt.figure(figsize=(12,4))
sns.kdeplot(df['SibSp'],color='blue',shade=True)
plt.show()

In [ ]:
# total precentage of the sex in dataframe
plt.title('Passengers by sex')
df['Sex'].value_counts().plot(kind='pie', autopct='%1.1f%%',labels=df['Sex'].unique())
plt.axis('equal')
plt.show()

In [ ]:
plt.title('Survived by sex')
df['Survived'].value_counts().plot(kind='pie', autopct='%1.1f%%',labels=df['Sex'].unique())
plt.axis('equal')
plt.show()

In [ ]:
# Survival rate by sex
passengers_by_sex = df['Sex'].value_counts()
survivors_by_sex = df[df['Survived'] == 1]['Sex'].value_counts()
survival_rates = survivors_by_sex / passengers_by_sex

In [ ]:
print("Survival rate by sex: ",survival_rates)

#### Correlation

In [ ]:
numerical_df = df.select_dtypes(include=['int64', 'float64'])
correlation_matrix = numerical_df.corr()
mask = np.triu(np.ones_like(correlation_matrix, dtype=bool))


plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, mask=mask, annot=True, fmt='.2f', square=True, linewidths=.5)

plt.show()

In [ ]:
pd.crosstab([df['Pclass'], df['Survived']], 
            df['Age_group']).plot(kind='bar',stacked=True,title='Pclass, Survived by Age_group',figsize=(12, 6))
plt.show()

In [ ]:
pclass_srvid_age_g = pd.crosstab([df['Pclass'], df['Survived']], df['Age_group'])

pclass_srvid_age_g

### 4. Observation
- **Class 1**: There is high survival rate of age group 19-40 while the other age_groups have low non-survival rate which belong to this (class 1) class.
- **Class 3**: There is low survival rate of age group 19-40.
- **Class 2**: The survival and non-survival are approximatily near and above to 50 which is age_group 19-40.

---

Thank you for exploring this notebook.
Please drop your opinion.